version: "3.7"

services: 

    nginx:
        build:
            context: ./NGINX
            dockerfile: Dockerfile
        image: forrow/NGINX
        ports:
            - "80:80"
        networks:
            - sfia2_network
        depends_on:
            - service_4
            - service_3
            - service_2
            - service_1
        deploy:
            replicas: 2

    service_1:
        build: ./Service_1
        image: forrow/service_1
        ports:
            - "5000:5000"
        networks:
            - sfia2_network
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PASS=${MYSQL_PASS}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_DBNAME=${MYSQL_DBNAME}
            - LOOT_SECRETKEY=${LOOT_SECRETKEY}
        depends_on:
            - service_4
            - service_3
            - service_2
        deploy:
            replicas: 2

    service_2:
        build: ./Service_2
        image: forrow/service_2
        networks:
            - sfia2_network
        deploy:
            replicas: 2

    service_3:
        build: ./Service_3
        image: forrow/service_3
        networks:
            - sfia2_network
        deploy:
            replicas: 2
    
    service_4:
        build: ./Service_4
        image: forrow/service_4
        networks:
            - sfia2_network
        deploy:
            replicas: 2



        
networks:
    sfia2_network:
        driver: overlay