version: "3.7"

services: 

    service_1:
        build: ./Service_1
        image: forrow/service_1
        ports:
            - "5000:5000"
        networks:
            - sfia2_network
        environment:
            - SQL_HOST=${MYSQL_HOST}
            - SQL_PASS=${MYSQL_PASS}
            - SQL_PORT=${MYSQL_PORT}
            - SQL_USER=${MYSQL_USER}
            - SQL_DBNAME=${MYSQL_DBNAME}
            - LOOT_SECRETKEY=${LOOT_SECRETKEY}
        depends_on:
            - service_4
            - service_3
            - service_2
        deploy:
            replicas: 2

    service_2:
        build: ./Service_2
        image: forrow/service_2
        networks:
            - sfia2_network
        deploy:
            replicas: 2

    service_3:
        build: ./Service_3
        image: forrow/service_3
        networks:
            - sfia2_network
        deploy:
            replicas: 2
    
    service_4:
        build: ./Service_4
        image: forrow/service_4
        networks:
            - sfia2_network
        deploy:
            replicas: 2
        
networks:
    sfia2_network:
        driver: overlay